server:
  port: 7071
spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
    jest:
      uris: http://127.0.0.1:9200
      read-timeout: 5000
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**

